services:
  - type: web
    name: vauice-backend
    env: python
    region: oregon
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi_socketio:application --bind 0.0.0.0:$PORT --worker-class gevent --workers 1"
    healthCheckPath: "/ping/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: WEB_CONCURRENCY
        value: 4
